#############################################################################
# Makefile for building: src
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  src.pro
# Template: subdirs
# Command: /opt/qt5/5.2.1/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile src.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /opt/qt5/5.2.1/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-lib \
		sub-include \
		sub-demo \
		sub-modules \
		sub-ext


sub-lib-qmake_all: sub-include-qmake_all FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && $(QMAKE) /home/muawijhe/Development/ccmain/src/lib/lib.pro -spec linux-g++ CONFIG+=debug -o Makefile
	cd lib/ && $(MAKE) -f Makefile qmake_all
sub-lib: sub-include FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/lib/lib.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-lib-make_first: sub-include-make_first FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/lib/lib.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-lib-all: sub-include-all FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/lib/lib.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-lib-clean: sub-include-clean FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/lib/lib.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-lib-distclean: sub-include-distclean FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/lib/lib.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-lib-install_subtargets: sub-include-install_subtargets FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/lib/lib.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-lib-uninstall_subtargets: sub-include-uninstall_subtargets FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/lib/lib.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-include-qmake_all:  FORCE
	@test -d include/ || mkdir -p include/
	cd include/ && $(QMAKE) /home/muawijhe/Development/ccmain/src/include/include.pro -spec linux-g++ CONFIG+=debug -o Makefile
	cd include/ && $(MAKE) -f Makefile qmake_all
sub-include: FORCE
	@test -d include/ || mkdir -p include/
	cd include/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/include/include.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-include-make_first: FORCE
	@test -d include/ || mkdir -p include/
	cd include/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/include/include.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-include-all: FORCE
	@test -d include/ || mkdir -p include/
	cd include/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/include/include.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-include-clean: FORCE
	@test -d include/ || mkdir -p include/
	cd include/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/include/include.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-include-distclean: FORCE
	@test -d include/ || mkdir -p include/
	cd include/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/include/include.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-include-install_subtargets: FORCE
	@test -d include/ || mkdir -p include/
	cd include/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/include/include.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-include-uninstall_subtargets: FORCE
	@test -d include/ || mkdir -p include/
	cd include/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/include/include.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-demo-qmake_all: sub-lib-qmake_all FORCE
	@test -d demo/ || mkdir -p demo/
	cd demo/ && $(QMAKE) /home/muawijhe/Development/ccmain/src/demo/demo.pro -spec linux-g++ CONFIG+=debug -o Makefile
	cd demo/ && $(MAKE) -f Makefile qmake_all
sub-demo: sub-lib FORCE
	@test -d demo/ || mkdir -p demo/
	cd demo/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/demo/demo.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-demo-make_first: sub-lib-make_first FORCE
	@test -d demo/ || mkdir -p demo/
	cd demo/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/demo/demo.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-demo-all: sub-lib-all FORCE
	@test -d demo/ || mkdir -p demo/
	cd demo/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/demo/demo.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-demo-clean: sub-lib-clean FORCE
	@test -d demo/ || mkdir -p demo/
	cd demo/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/demo/demo.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-demo-distclean: sub-lib-distclean FORCE
	@test -d demo/ || mkdir -p demo/
	cd demo/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/demo/demo.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-demo-install_subtargets: sub-lib-install_subtargets FORCE
	@test -d demo/ || mkdir -p demo/
	cd demo/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/demo/demo.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-demo-uninstall_subtargets: sub-lib-uninstall_subtargets FORCE
	@test -d demo/ || mkdir -p demo/
	cd demo/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/demo/demo.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-modules-qmake_all: sub-lib-qmake_all FORCE
	@test -d modules/ || mkdir -p modules/
	cd modules/ && $(QMAKE) /home/muawijhe/Development/ccmain/src/modules/modules.pro -spec linux-g++ CONFIG+=debug -o Makefile
	cd modules/ && $(MAKE) -f Makefile qmake_all
sub-modules: sub-lib FORCE
	@test -d modules/ || mkdir -p modules/
	cd modules/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/modules/modules.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-modules-make_first: sub-lib-make_first FORCE
	@test -d modules/ || mkdir -p modules/
	cd modules/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/modules/modules.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-modules-all: sub-lib-all FORCE
	@test -d modules/ || mkdir -p modules/
	cd modules/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/modules/modules.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-modules-clean: sub-lib-clean FORCE
	@test -d modules/ || mkdir -p modules/
	cd modules/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/modules/modules.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-modules-distclean: sub-lib-distclean FORCE
	@test -d modules/ || mkdir -p modules/
	cd modules/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/modules/modules.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-modules-install_subtargets: sub-lib-install_subtargets FORCE
	@test -d modules/ || mkdir -p modules/
	cd modules/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/modules/modules.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-modules-uninstall_subtargets: sub-lib-uninstall_subtargets FORCE
	@test -d modules/ || mkdir -p modules/
	cd modules/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/modules/modules.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-ext-qmake_all:  FORCE
	@test -d ext/ || mkdir -p ext/
	cd ext/ && $(QMAKE) /home/muawijhe/Development/ccmain/src/ext/ext.pro -spec linux-g++ CONFIG+=debug -o Makefile
	cd ext/ && $(MAKE) -f Makefile qmake_all
sub-ext: FORCE
	@test -d ext/ || mkdir -p ext/
	cd ext/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/ext/ext.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-ext-make_first: FORCE
	@test -d ext/ || mkdir -p ext/
	cd ext/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/ext/ext.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-ext-all: FORCE
	@test -d ext/ || mkdir -p ext/
	cd ext/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/ext/ext.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-ext-clean: FORCE
	@test -d ext/ || mkdir -p ext/
	cd ext/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/ext/ext.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-ext-distclean: FORCE
	@test -d ext/ || mkdir -p ext/
	cd ext/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/ext/ext.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ext-install_subtargets: FORCE
	@test -d ext/ || mkdir -p ext/
	cd ext/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/ext/ext.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-ext-uninstall_subtargets: FORCE
	@test -d ext/ || mkdir -p ext/
	cd ext/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/ext/ext.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: src.pro /opt/qt5/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf /opt/qt5/5.2.1/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/common/unix.conf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/common/linux.conf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/common/g++-base.conf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/qconfig.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5/5.2.1/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/features/qt_config.prf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/features/spec_post.prf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/features/default_pre.prf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/features/default_post.prf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/features/warn_on.prf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/features/exceptions.prf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/features/yacc.prf \
		/opt/qt5/5.2.1/gcc_64/mkspecs/features/lex.prf \
		src.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile src.pro
/opt/qt5/5.2.1/gcc_64/mkspecs/features/spec_pre.prf:
/opt/qt5/5.2.1/gcc_64/mkspecs/common/shell-unix.conf:
/opt/qt5/5.2.1/gcc_64/mkspecs/common/unix.conf:
/opt/qt5/5.2.1/gcc_64/mkspecs/common/linux.conf:
/opt/qt5/5.2.1/gcc_64/mkspecs/common/gcc-base.conf:
/opt/qt5/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/qt5/5.2.1/gcc_64/mkspecs/common/g++-base.conf:
/opt/qt5/5.2.1/gcc_64/mkspecs/common/g++-unix.conf:
/opt/qt5/5.2.1/gcc_64/mkspecs/qconfig.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt5/5.2.1/gcc_64/mkspecs/features/qt_functions.prf:
/opt/qt5/5.2.1/gcc_64/mkspecs/features/qt_config.prf:
/opt/qt5/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/qt5/5.2.1/gcc_64/mkspecs/features/spec_post.prf:
/opt/qt5/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/qt5/5.2.1/gcc_64/mkspecs/features/default_pre.prf:
/opt/qt5/5.2.1/gcc_64/mkspecs/features/resolve_config.prf:
/opt/qt5/5.2.1/gcc_64/mkspecs/features/default_post.prf:
/opt/qt5/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
/opt/qt5/5.2.1/gcc_64/mkspecs/features/warn_on.prf:
/opt/qt5/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/qt5/5.2.1/gcc_64/mkspecs/features/exceptions.prf:
/opt/qt5/5.2.1/gcc_64/mkspecs/features/yacc.prf:
/opt/qt5/5.2.1/gcc_64/mkspecs/features/lex.prf:
src.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile src.pro

qmake_all: sub-lib-qmake_all sub-include-qmake_all sub-demo-qmake_all sub-modules-qmake_all sub-ext-qmake_all FORCE

make_first: sub-lib-make_first sub-include-make_first sub-demo-make_first sub-modules-make_first sub-ext-make_first FORCE
all: sub-lib-all sub-include-all sub-demo-all sub-modules-all sub-ext-all FORCE
clean: sub-lib-clean sub-include-clean sub-demo-clean sub-modules-clean sub-ext-clean FORCE
distclean: sub-lib-distclean sub-include-distclean sub-demo-distclean sub-modules-distclean sub-ext-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-lib-install_subtargets sub-include-install_subtargets sub-demo-install_subtargets sub-modules-install_subtargets sub-ext-install_subtargets FORCE
uninstall_subtargets: sub-lib-uninstall_subtargets sub-include-uninstall_subtargets sub-demo-uninstall_subtargets sub-modules-uninstall_subtargets sub-ext-uninstall_subtargets FORCE

sub-lib-check: sub-include-check
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/lib/lib.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-include-check:
	@test -d include/ || mkdir -p include/
	cd include/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/include/include.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-demo-check: sub-lib-check
	@test -d demo/ || mkdir -p demo/
	cd demo/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/demo/demo.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-modules-check: sub-lib-check
	@test -d modules/ || mkdir -p modules/
	cd modules/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/modules/modules.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-ext-check:
	@test -d ext/ || mkdir -p ext/
	cd ext/ && ( test -e Makefile || $(QMAKE) /home/muawijhe/Development/ccmain/src/ext/ext.pro -spec linux-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-lib-check sub-include-check sub-demo-check sub-modules-check sub-ext-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

