/* Auto-generated by genmsg_cpp for file /home/muawijhe/Development/ccmain/src/cc_msgs/msg/BARORaw.msg */
#ifndef CC_MSGS_MESSAGE_BARORAW_H
#define CC_MSGS_MESSAGE_BARORAW_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace cc_msgs
{
template <class ContainerAllocator>
struct BARORaw_ {
  typedef BARORaw_<ContainerAllocator> Type;

  BARORaw_()
  : header()
  , temperature_degC(0.0)
  , pressure_mbar(0.0)
  {
  }

  BARORaw_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , temperature_degC(0.0)
  , pressure_mbar(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _temperature_degC_type;
  double temperature_degC;

  typedef double _pressure_mbar_type;
  double pressure_mbar;


  typedef boost::shared_ptr< ::cc_msgs::BARORaw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cc_msgs::BARORaw_<ContainerAllocator>  const> ConstPtr;
}; // struct BARORaw
typedef  ::cc_msgs::BARORaw_<std::allocator<void> > BARORaw;

typedef boost::shared_ptr< ::cc_msgs::BARORaw> BARORawPtr;
typedef boost::shared_ptr< ::cc_msgs::BARORaw const> BARORawConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cc_msgs::BARORaw_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cc_msgs::BARORaw_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cc_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cc_msgs::BARORaw_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cc_msgs::BARORaw_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cc_msgs::BARORaw_<ContainerAllocator> > {
  static const char* value() 
  {
    return "53c7285c527cd70735262bb1e0d615e5";
  }

  static const char* value(const  ::cc_msgs::BARORaw_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x53c7285c527cd707ULL;
  static const uint64_t static_value2 = 0x35262bb1e0d615e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::cc_msgs::BARORaw_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cc_msgs/BARORaw";
  }

  static const char* value(const  ::cc_msgs::BARORaw_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cc_msgs::BARORaw_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64 temperature_degC\n\
float64 pressure_mbar\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::cc_msgs::BARORaw_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::cc_msgs::BARORaw_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::cc_msgs::BARORaw_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cc_msgs::BARORaw_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.temperature_degC);
    stream.next(m.pressure_mbar);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BARORaw_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cc_msgs::BARORaw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cc_msgs::BARORaw_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "temperature_degC: ";
    Printer<double>::stream(s, indent + "  ", v.temperature_degC);
    s << indent << "pressure_mbar: ";
    Printer<double>::stream(s, indent + "  ", v.pressure_mbar);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CC_MSGS_MESSAGE_BARORAW_H

