/* Auto-generated by genmsg_cpp for file /home/muawijhe/Development/ccmain/src/cc_msgs/msg/GPSRaw.msg */
#ifndef CC_MSGS_MESSAGE_GPSRAW_H
#define CC_MSGS_MESSAGE_GPSRAW_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace cc_msgs
{
template <class ContainerAllocator>
struct GPSRaw_ {
  typedef GPSRaw_<ContainerAllocator> Type;

  GPSRaw_()
  : header()
  , gps_time_s()
  , latitude_deg(0.0)
  , longitude_deg(0.0)
  , altitude_m(0.0)
  {
  }

  GPSRaw_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , gps_time_s()
  , latitude_deg(0.0)
  , longitude_deg(0.0)
  , altitude_m(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef ros::Time _gps_time_s_type;
  ros::Time gps_time_s;

  typedef double _latitude_deg_type;
  double latitude_deg;

  typedef double _longitude_deg_type;
  double longitude_deg;

  typedef double _altitude_m_type;
  double altitude_m;


  typedef boost::shared_ptr< ::cc_msgs::GPSRaw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cc_msgs::GPSRaw_<ContainerAllocator>  const> ConstPtr;
}; // struct GPSRaw
typedef  ::cc_msgs::GPSRaw_<std::allocator<void> > GPSRaw;

typedef boost::shared_ptr< ::cc_msgs::GPSRaw> GPSRawPtr;
typedef boost::shared_ptr< ::cc_msgs::GPSRaw const> GPSRawConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cc_msgs::GPSRaw_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cc_msgs::GPSRaw_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cc_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cc_msgs::GPSRaw_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cc_msgs::GPSRaw_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cc_msgs::GPSRaw_<ContainerAllocator> > {
  static const char* value() 
  {
    return "33fd13ec9730c956eb074f572aa0712f";
  }

  static const char* value(const  ::cc_msgs::GPSRaw_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x33fd13ec9730c956ULL;
  static const uint64_t static_value2 = 0xeb074f572aa0712fULL;
};

template<class ContainerAllocator>
struct DataType< ::cc_msgs::GPSRaw_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cc_msgs/GPSRaw";
  }

  static const char* value(const  ::cc_msgs::GPSRaw_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cc_msgs::GPSRaw_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
time    gps_time_s\n\
float64 latitude_deg\n\
float64 longitude_deg\n\
float64 altitude_m\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::cc_msgs::GPSRaw_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::cc_msgs::GPSRaw_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::cc_msgs::GPSRaw_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cc_msgs::GPSRaw_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.gps_time_s);
    stream.next(m.latitude_deg);
    stream.next(m.longitude_deg);
    stream.next(m.altitude_m);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GPSRaw_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cc_msgs::GPSRaw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cc_msgs::GPSRaw_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gps_time_s: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.gps_time_s);
    s << indent << "latitude_deg: ";
    Printer<double>::stream(s, indent + "  ", v.latitude_deg);
    s << indent << "longitude_deg: ";
    Printer<double>::stream(s, indent + "  ", v.longitude_deg);
    s << indent << "altitude_m: ";
    Printer<double>::stream(s, indent + "  ", v.altitude_m);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CC_MSGS_MESSAGE_GPSRAW_H

