"""autogenerated by genpy from cc_msgs/IMURaw.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class IMURaw(genpy.Message):
  _md5sum = "19d8a1835e5dba2215abcf6e2f5ef1f7"
  _type = "cc_msgs/IMURaw"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
geometry_msgs/Vector3 linear_acceleration_g
geometry_msgs/Vector3 angular_speed_deg_s
geometry_msgs/Vector3 magnetic_field_uT
float64 temperature_degC

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
"""
  __slots__ = ['header','linear_acceleration_g','angular_speed_deg_s','magnetic_field_uT','temperature_degC']
  _slot_types = ['std_msgs/Header','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,linear_acceleration_g,angular_speed_deg_s,magnetic_field_uT,temperature_degC

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IMURaw, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.linear_acceleration_g is None:
        self.linear_acceleration_g = geometry_msgs.msg.Vector3()
      if self.angular_speed_deg_s is None:
        self.angular_speed_deg_s = geometry_msgs.msg.Vector3()
      if self.magnetic_field_uT is None:
        self.magnetic_field_uT = geometry_msgs.msg.Vector3()
      if self.temperature_degC is None:
        self.temperature_degC = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.linear_acceleration_g = geometry_msgs.msg.Vector3()
      self.angular_speed_deg_s = geometry_msgs.msg.Vector3()
      self.magnetic_field_uT = geometry_msgs.msg.Vector3()
      self.temperature_degC = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_10d.pack(_x.linear_acceleration_g.x, _x.linear_acceleration_g.y, _x.linear_acceleration_g.z, _x.angular_speed_deg_s.x, _x.angular_speed_deg_s.y, _x.angular_speed_deg_s.z, _x.magnetic_field_uT.x, _x.magnetic_field_uT.y, _x.magnetic_field_uT.z, _x.temperature_degC))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.linear_acceleration_g is None:
        self.linear_acceleration_g = geometry_msgs.msg.Vector3()
      if self.angular_speed_deg_s is None:
        self.angular_speed_deg_s = geometry_msgs.msg.Vector3()
      if self.magnetic_field_uT is None:
        self.magnetic_field_uT = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.linear_acceleration_g.x, _x.linear_acceleration_g.y, _x.linear_acceleration_g.z, _x.angular_speed_deg_s.x, _x.angular_speed_deg_s.y, _x.angular_speed_deg_s.z, _x.magnetic_field_uT.x, _x.magnetic_field_uT.y, _x.magnetic_field_uT.z, _x.temperature_degC,) = _struct_10d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_10d.pack(_x.linear_acceleration_g.x, _x.linear_acceleration_g.y, _x.linear_acceleration_g.z, _x.angular_speed_deg_s.x, _x.angular_speed_deg_s.y, _x.angular_speed_deg_s.z, _x.magnetic_field_uT.x, _x.magnetic_field_uT.y, _x.magnetic_field_uT.z, _x.temperature_degC))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.linear_acceleration_g is None:
        self.linear_acceleration_g = geometry_msgs.msg.Vector3()
      if self.angular_speed_deg_s is None:
        self.angular_speed_deg_s = geometry_msgs.msg.Vector3()
      if self.magnetic_field_uT is None:
        self.magnetic_field_uT = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.linear_acceleration_g.x, _x.linear_acceleration_g.y, _x.linear_acceleration_g.z, _x.angular_speed_deg_s.x, _x.angular_speed_deg_s.y, _x.angular_speed_deg_s.z, _x.magnetic_field_uT.x, _x.magnetic_field_uT.y, _x.magnetic_field_uT.z, _x.temperature_degC,) = _struct_10d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_10d = struct.Struct("<10d")
